name: "Minecraft Bedrock Action: Create MCWorld"
description: "The github action that will create a mcworld in a given respository"
branding:
  icon: box
  color: green
inputs:
  folder:
    description: The folder path to start at
    required: true
  processJson:
    description: Whether or not to format json and minify json
    required: false
    default: true
  trimFiles:
    description: Whether or not to remove unwanted files
    required: false
    default: true
  outputFile:
    description: Defaults to the folder above the specified source folder with file name: word.mcworld, but this parameter can be overwritten.
    required: false
    default: ''
    
outputs:
  worldFilepath:
    description: "The outputted mcworld filepath"
runs:
  using: "node12"
  main: "dist/index.js"
