name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"        
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
