name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Build
        run: npm ci
      - run: npm run build
      - name: Test
        run: npm test
      - name: commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "Blockception@github.com"
          git config --global user.name "Blockception Bot"
          git add .
          git commit -m "auto: generated distribution"
          git push

  publish-tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"        
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
